# Generated by Django 4.2.2 on 2023-08-14 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0002_source_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='source',
            old_name='avatar',
            new_name='logo',
        ),
    ]
