# Generated by Django 4.2.2 on 2023-08-25 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0003_rename_avatar_source_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='code_name',
            field=models.CharField(default=1, max_length=64, verbose_name='Code Name'),
            preserve_default=False,
        ),
    ]
