# Generated by Django 4.2.2 on 2023-07-12 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0003_rename_currency_type_rate_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('source_url', models.URLField(max_length=255)),
                ('phone', models.CharField(max_length=13)),
            ],
        ),
    ]
