# Generated by Django 4.2.2 on 2023-08-25 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0004_source_code_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='code_name',
            field=models.CharField(max_length=64, unique=True, verbose_name='Code Name'),
        ),
    ]
