# Generated by Django 4.2.2 on 2023-07-29 08:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0005_alter_rate_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestResponseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=100)),
                ('request_method', models.CharField(max_length=100)),
                ('time', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='contact_us',
            options={'verbose_name': 'Contact Us', 'verbose_name_plural': 'Contact Us'},
        ),
        migrations.AlterModelOptions(
            name='rate',
            options={'verbose_name': 'Rate', 'verbose_name_plural': 'Rates'},
        ),
        migrations.AlterModelOptions(
            name='source',
            options={'verbose_name': 'Source', 'verbose_name_plural': 'Sources'},
        ),
        migrations.AlterField(
            model_name='contact_us',
            name='email_from',
            field=models.CharField(max_length=256, validators=[django.core.validators.EmailValidator], verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='contact_us',
            name='message',
            field=models.CharField(max_length=300, verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='contact_us',
            name='subject',
            field=models.CharField(max_length=100, verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='buy',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Buy'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='currency',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Dollar'), (2, 'Euro')], default=1, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='sell',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Sell'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='source',
            field=models.CharField(max_length=68, verbose_name='Source'),
        ),
        migrations.AlterField(
            model_name='source',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='source',
            name='phone',
            field=models.CharField(max_length=13, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='source',
            name='source_url',
            field=models.URLField(max_length=255, verbose_name='URL'),
        ),
    ]
