# Generated by Django 4.2.2 on 2023-07-29 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0006_requestresponselog_alter_contact_us_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestresponselog',
            name='time',
            field=models.TimeField(),
        ),
    ]
