# Generated by Django 4.2.2 on 2023-07-29 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0007_alter_requestresponselog_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestresponselog',
            name='time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
